name: Update Table

on:
  push:
    paths:
      - 'data/repositories.yaml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
        npm install -g prettier
    
    - name: Update table
      run: ./scripts/update_table.sh
    
    - name: Commit changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "🤖 Auto-update table"
          git push
        fi
